  steps:
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'version']
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'test']
    dir: 'function/dir/from/repo/root'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'Get', '--runtime=go113', '--trigger-http', '--region=europe-west1']
    dir: 'functions'