steps:
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'version']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'CommentGet', '--runtime=go113', '--trigger-http', '--region=europe-west1']
    dir: 'functions'

#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['functions', 'deploy', 'CommentGetAll', '--runtime=go113', '--trigger-http', '--region=europe-west1']
#    dir: 'functions'

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['functions', 'deploy', 'CommentCreate', '--runtime=go113', '--trigger-http', '--region=europe-west1']
#   dir: 'functions'

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['functions', 'deploy', 'CommentUpdate', '--runtime=go113', '--trigger-http', '--region=europe-west1']
#   dir: 'functions'