steps:
  - name: golang
    args: ['go', 'build', '.']
    dir: 'functions'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'Get', '--runtime=go113', '--trigger-http', '--region=europe-west1']
    dir: 'functions'
