steps:
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'version']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'comment-update', '--runtime=go113', '--trigger-http', '--region=europe-west1' ,'--entry-point=CommentUpdate']
    dir: 'functions'